export enum RoleType {
  ROLE_PATIENT = 'ROLE_PATIENT',
  ROLE_PHARMACIST = 'ROLE_PHARMACIST',
  ROLE_DERMATOLOGIST = 'ROLE_DERMATOLOGIST',
  ROLE_PHARMACY_ADMIN = 'ROLE_PHARMACY_ADMIN',
  ROLE_SYSTEM_ADMIN = 'ROLE_SYSTEM_ADMIN',
  ROLE_SUPPLIER = 'ROLE_SUPPLIER',
}
